site_name: drfsc for distributed Feature Selection
edit_uri: 'blob/main/docs/'
nav:
  - Home: index.md
  - 'Getting Started': 
    - fitting single models: notebooks/01_fitting_single.ipynb
    - fitting ensembles: notebooks/02_fitting_ensemble.ipynb
  - DRFSC API Docs: drfsc_api.md
  - RFSC_base API Docs: rfsc_base_api.md
  - RFSC API Docs: rfsc_api.md
  - utils: utils.md
  - Removing Correlated Features: removing_correlated_features.md
theme:
  name: "material"
repo_url: https://github.com/markcc309/drfsc
plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: "numpy"
          setup_commands:
            - import sys
            - sys.path.append("src")
          rendering:
            show_source: false
      custom_templates: templates